version: "3"

services:
  nginx-react-app:
    restart: always
    image: nginx-react-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    stdin_open: true
    tty: true
